### ISSUE TITLE
Errors when running the game on Linux

### ISSUE THREAD

**Issue by haykerman** [Nneji123/Alien-Shooter#1]
alien_shooter.py:115: SyntaxWarning: "is" with a literal. Did you mean "=="?

ModuleNotFoundError: No module named 'tkinter'

**Comment by Nneji123** [comment]
Do you have pygame installed?

**Comment by haykerman** [comment]
I've installed it and now there are other errors:

SyntaxWarning: "is" with a literal. Did you mean "=="?

And another one is, it's trying to load images with local path on your PC. 

FileNotFoundError: No file 'C:\Users\IFEANYI PC\Documents\Space Invaders\background.png' found in working directory

**Comment by haykerman** [comment]
All your file paths are absolute paths pointing to your PC. Those should be relative to the user's working directory.

**Comment by Nneji123** [comment]
Okay I'll try and fix the paths issue. Thanks

**Comment by Nneji123** [comment]
Oh btw how did you find my repository if I may ask?

**Comment by haykerman** [comment]
> Oh btw how did you find my repository if I may ask?

I've read your Hashnode article :)

**Comment by haykerman** [comment]
No such file or directory: 'SPACEBOY.ttf'
This actual font is SPACEBOY.TTF (notice the extension case)

On some operating systems, paths are case sensitive.
So this should be handled too.

**Comment by Nneji123** [comment]
Oh thanks a lot I didn't know that. I've not used Linux before so I didn't get those issues but I'll rectify it.

**Comment by haykerman** [comment]
You're welcome. Good job, btw ;)
